Sign in page
AlexShavkuta/BeardRequests pull request #10
Opened 2023-08-07 15:04 UTC by AviadCohen24

Created sign in page

2023-08-07 20:25 UTC, AlexShavkuta requested changes

2023-08-07 20:25 UTC, AlexShavkuta commented on Frontend/beard-requests/src/App.js
> +  const handleDrawerClick = () => setIsDrawerOpen(!isDrawerOpen);
Use prevStare instead

2023-08-07 20:25 UTC, AlexShavkuta commented on Frontend/beard-requests/src/Components/form-input/FormInput.component.jsx
> +    const handleInputChange = (event) => onChange(event.target.value)
When there is a single parameter don’t use parentheses

2023-08-07 20:25 UTC, AlexShavkuta commented on Frontend/beard-requests/src/Routes/nav-bar/NavBar.component.jsx
> +    const handleDrawerClick = () => changeOpenHandler();
Why did you implement it that way?

2023-08-07 20:25 UTC, AlexShavkuta commented on Frontend/beard-requests/src/Routes/nav-bar/NavBar.styles.js
Excellent use of styled components!

2023-08-07 20:25 UTC, AlexShavkuta commented on Frontend/beard-requests/src/Utils/Server.js
> +export const checkAuthentication = async(personalNumber, password) => {
Add validation for the parameters, so you won’t be able to send to the server empty parameters.

2023-08-08 06:05 UTC, ShacharDahan commented on Frontend/beard-requests/src/Utils/Server.js
> +export const checkAuthentication = async(personalNumber, password) => {
in line 14 of Form.component.jsx there is validation checks for the parameters

2023-08-08 06:07 UTC, closed without merging